### PR TITLE
create legacy boot image

### PR DESCRIPTION
**Pull request by phip1611**
This MR introduces the `make bootimage` command that enables to boot everything on a USB flash drive.

### CODE REVIEW

**Comment by phip1611** [comment]
Hey @lonnietc, can you please verify if that works for you?

**Comment by lonnietc** [comment]
Hello, @phip1611 

I tried the "make bootimage" but it did not work at all:

```
diplomarbeit-impl$ make bootImage
make: *** No rule to make target 'bootImage'.  Stop.
```

**Comment by phip1611** [comment]
> make bootImage

it's lowercase. `bootimage`

**Comment by lonnietc** [comment]
yea, sorry for that but I actually tried it as "make bootimage" all lowercase.

I just typed with uppercase when I replied. fast fingers on the keyboard. Oops.

```
diplomarbeit-impl$ make bootimage
make: *** No rule to make target 'bootimage'.  Stop.
```

**Comment by phip1611** [comment]
ahh. You have to switch to the branch `legacy-boot`. `git fetch && git checkout legacy-boot`

**Comment by lonnietc** [comment]
I just tried,

```
$ git clone https://github.com/phip1611/diplomarbeit-impl.git

$ cd diplomarbeit-impl

$ git fetch && git checkout legacy-boot
```

It says:

Already on 'legacy-boot'
Your branch is up to date with 'origin/legacy-boot'.

but it did not pull thesis-hedron-fork or Libc-musl into mu local.

**Comment by phip1611** [comment]
You also have to follow the other steps from the README, like initializing the sub modules

https://github.com/phip1611/diplomarbeit-impl

**Comment by lonnietc** [comment]
Ok, this process seems to work:

```
$ git clone --recursive https://github.com/phip1611/diplomarbeit-impl.git

$ cd diplomarbeit-impl

$ git fetch && git checkout legacy-boot

$ make

$ make bootimage
```

Now we are getting closer, my friend.

**Comment by phip1611** [comment]
I don't know how useful this will be in the end, as the roottask won't print to the VGA buffer. It only writes to the serial device. However, if you can access the serial device of your machine for example via Intel AMT or via physical access then you will see something. 

This limitation is also described in the latest README

**Pull request merged**
